#!/usr/bin/env python3
"""
DAST Triage Agent - Analyzes ZAP findings with Claude AI
"""
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

def run_triage(report_path, output_dir):
    """Analyze ZAP report with Claude"""
    
    with open(report_path) as f:
        report = json.load(f)
    
    # Extract vulnerabilities
    findings = []
    for site in report.get('site', []):
        for alert in site.get('alerts', []):
            finding = {
                'id': alert.get('pluginid'),
                'name': alert.get('alert'),
                'risk': alert.get('riskdesc', '').split()[0],
                'confidence': alert.get('confidence'),
                'description': alert.get('desc')[:500],
                'count': len(alert.get('instances', [])),
                'instances': alert.get('instances', [])[:2]  # Sample 2
            }
            findings.append(finding)
    
    if not findings:
        print("No findings to analyze")
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        with open(output_dir / 'analysis.md', 'w') as f:
            f.write("# DAST Analysis\n\n✅ No vulnerabilities found!\n")
        return
    
    # Prepare Claude prompt
    prompt = f"""Analyze these security findings from an automated web app scan.

For each finding, decide:
1. **True Positive** - Real vulnerability that needs fixing
2. **False Positive** - Scanner error, not a real issue
3. **Needs Review** - Unsure, needs manual verification

Here are the findings ({len(findings)} total):

"""
    
    for i, finding in enumerate(findings[:10], 1):  # Limit to 10 findings
        prompt += f"""
**{i}. {finding['risk']} - {finding['name']}** (found {finding['count']}x)
- Confidence: {finding['confidence']}
- Description: {finding['description']}
- Instance: {json.dumps(finding['instances'][0] if finding['instances'] else {}, indent=2)[:200]}

"""
    
    prompt += """
Output as markdown with:
- ✅ True Positives (real issues)
- ⚠️ False Positives (scanner errors)  
- 🔍 Needs Review (uncertain)

Be concise. List each finding on one line with your verdict."""
    
    print("Sending findings to Claude for analysis...")
    print(f"Analyzing {len(findings)} findings...")
    
    try:
        # Call Claude CLI
        result = subprocess.run(
            ['claude', '-p', prompt, '--output-format', 'json'],
            capture_output=True,
            text=True,
            timeout=120,
            env={
                **os.environ,
                'CLAUDE_CODE_OAUTH_TOKEN': os.environ.get('CLAUDE_CODE_OAUTH_TOKEN', '')
            }
        )
        
        if result.returncode != 0:
            print(f"Error: {result.stderr}")
            analysis = "Claude analysis failed. Check raw report."
        else:
            try:
                data = json.loads(result.stdout)
                analysis = data.get('result', 'No response from Claude')
            except:
                analysis = result.stdout[:1000]
    
    except FileNotFoundError:
        print("Error: 'claude' command not found")
        print("Run: npm install -g @anthropic-ai/claude-code")
        analysis = "Claude CLI not installed"
    
    # Write analysis to file
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    with open(output_dir / 'analysis.md', 'w') as f:
        f.write(f"""# DAST Findings Analysis

**Scan Date:** Generated by Claude AI analysis
**Total Findings:** {len(findings)}

---

## Claude's Analysis

{analysis}

---

## Raw Findings Summary

| Risk | Name | Count |
|---|---|---|
""")
        for finding in findings:
            f.write(f"| {finding['risk']} | {finding['name']} | {finding['count']} |\n")
    
    print(f"✅ Analysis saved to {output_dir}/analysis.md")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python triage.py <report.json> [--out-dir OUTPUT_DIR]")
        sys.exit(1)
    
    report_file = sys.argv[1]
    output_dir = 'triage'
    
    if '--out-dir' in sys.argv:
        idx = sys.argv.index('--out-dir')
        output_dir = sys.argv[idx + 1]
    
    run_triage(report_file, output_dir)
